# Generated by Django 2.1.1 on 2019-03-11 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('minimum', models.IntegerField()),
                ('maximum', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='factory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.Factory'),
        ),
    ]
